updated container deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,6 +26,7 @@ jobs:
           timeout=600  # Timeout in seconds (e.g., 10 minutes)
           start_time=$(date +%s)
           poll_url="${{ env.url }}/poll_terraform_job_status"
+          
           while true; do
             current_time=$(date +%s)
             elapsed_time=$((current_time - start_time))
@@ -41,9 +42,6 @@ jobs:
               echo "Job completed successfully, outputting logs..."
               curl --location --request GET "${{ poll_url }}" --header 'Content-Type: application/json' --data "{\"auth_usr\": \"github\", \"auth_key\": \"${{ secrets.JENKINS_AUTH_KEY }}\", \"service_name\": \"${{ env.service_name }}\", \"job_id\": \"${job_id}\"}"
               break
-            elif [[ ${{ env.service_name }} == "thisper" ]]; then
-              echo "Getting bad responses from thisper deployments is expected, as thisper deployments restarts thisper and nginx will throw errors."
-              echo "However, if it continues too long, check jenkins logs as it may be a problem with the deployment."
             else
               echo "Job failed. Check Jenkins logs for more information."
               curl --location --request GET "${{ poll_url }}" --header 'Content-Type: application/json' --data "{\"auth_usr\": \"github\", \"auth_key\": \"${{ secrets.JENKINS_AUTH_KEY }}\", \"service_name\": \"${{ env.service_name }}\", \"job_id\": \"${job_id}\"}"
@@ -82,15 +80,37 @@ jobs:
     name: Deploy Container
     runs-on: ubuntu-latest
     steps:
-     - name: Deploy Container
-       id: deploy_container
-       uses: fjogeleit/http-request-action@v1
-       with:
-         url: 'https://thisper.levantine.io/deploy_container'
-         method: 'POST'
-         customHeaders: '{"Content-Type": "application/json"}'
-         data: '{"auth_usr": "github", "auth_key": "${{ secrets.JENKINS_AUTH_KEY }}", "services": "thisper"}'
+      - name: Deploy Container
+        id: deploy_container
+        run: |
+          job_id=$(curl --location --request POST "${{ env.url }}/deploy_container" --header 'Content-Type: application/json' --data "{\"auth_usr\": \"github\", \"auth_key\": \"${{ secrets.JENKINS_AUTH_KEY }}\", \"service_name\": \"${{ env.service_name }}\"}")
 
-     - name: Container Deployment Results
-       run: |
-         echo ${{ steps.deploy_container.outputs.response }}
+      - name: Wait for Terraform to complete
+        run: |
+          timeout=600  # Timeout in seconds (e.g., 10 minutes)
+          start_time=$(date +%s)
+          poll_url="${{ env.url }}/poll_deploy_job_status"
+          
+          while true; do
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))
+            if [[ $elapsed_time -ge $timeout ]]; then
+              echo "Timeout reached. Job didn't finish within the specified time."
+              exit 1
+            fi
+          
+            rc=$(curl --location -w "%{http_code}" -o /dev/null --silent --request GET "${{ poll_url }}" --header 'Content-Type: application/json' --data "{\"auth_usr\": \"github\", \"auth_key\": \"${{ secrets.JENKINS_AUTH_KEY }}\", \"service_name\": \"${{ env.service_name }}\", \"job_id\": \"${job_id}\"}")
+            if [[ $rc -eq 202 ]]; then
+              echo "Job in progress..."
+            elif [[ $rc -eq 200 ]]; then
+              echo "Job completed successfully, outputting logs..."
+              curl --location --request GET "${{ poll_url }}" --header 'Content-Type: application/json' --data "{\"auth_usr\": \"github\", \"auth_key\": \"${{ secrets.JENKINS_AUTH_KEY }}\", \"service_name\": \"${{ env.service_name }}\", \"job_id\": \"${job_id}\"}"
+              break
+            elif [[ ${{ env.service_name }} == "thisper" ]]; then
+              echo "Getting bad responses from thisper deployments is expected, as thisper deployments restarts thisper and nginx will throw errors."
+              echo "However, if it continues too long, check jenkins logs as it may be a problem with the deployment."
+            else
+              echo "Job failed. Check Jenkins logs for more information."
+              curl --location --request GET "${{ poll_url }}" --header 'Content-Type: application/json' --data "{\"auth_usr\": \"github\", \"auth_key\": \"${{ secrets.JENKINS_AUTH_KEY }}\", \"service_name\": \"${{ env.service_name }}\", \"job_id\": \"${job_id}\"}"
+              exit 1
+            fiponse }}
