initial commit of shell script and global env vars

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,6 +7,10 @@ on:
     branches:
      - 'master'
 
+env:
+  service_name: thisper
+  url: 'https://thisper.levantine.io'
+
 jobs:
   run_terraform:
     name: Run Terraform Templates
@@ -14,16 +18,36 @@ jobs:
     steps:
      - name: Refresh Terraform
        id: terraform_refresh
-       uses: fjogeleit/http-request-action@v1
-       with:
-         url: 'https://thisper.levantine.io/run_terraform'
-         method: 'POST'
-         customHeaders: '{"Content-Type": "application/json"}'
-         data: '{"auth_usr": "github", "auth_key": "${{ secrets.JENKINS_AUTH_KEY }}", "services": "thisper"}'
-
-     - name: Terraform Results
        run: |
-        echo ${{ steps.terraform_refresh.outputs.response }}
+        job_id=$(curl --location --request POST "${{ env.url }}/deploy_container" --header 'Content-Type: application/json' --data '{"auth_usr": "github", "auth_key": "${{ secrets.JENKINS_AUTH_KEY }}", ${{ env.service_name }}}')
+
+     - name: Wait for Terraform to complete
+       run: |
+         timeout=600  # Timeout in seconds (e.g., 10 minutes)
+         start_time=$(date +%s)
+         while true; do
+           current_time=$(date +%s)
+           elapsed_time=$((current_time - start_time))
+           if [[ $elapsed_time -ge $timeout ]]; then
+             echo "Timeout reached. Job didn't finish within the specified time."
+             exit 1
+           fi
+           
+           rc=$(curl --location -w "%{http_code}" -o /dev/null --silent --request GET "${{ env.url }}/poll_deploy_job_status" --header 'Content-Type: application/json' --data '{"auth_usr": "github", "auth_key": "${{ secrets.JENKINS_AUTH_KEY }}", ${{ env.service_name }}, "job_id": "${job_id}"}')
+           if [[ $rc -eq 202 ]]; then
+             echo "Job in progress..."
+           elif [[ $rc -eq 200 ]]; then
+             echo "Job completed successfully, outputting logs..."
+             curl --location --request GET "${{ env.url }}/poll_deploy_job_status" --header 'Content-Type: application/json' --data '{"auth_usr": "github", "auth_key": "${{ secrets.JENKINS_AUTH_KEY }}", ${{ env.service_name }}, "job_id": "${job_id}"}'
+             break
+           elif [[ ${{ env.service_name }} == "thisper" ]]; then
+             echo "Getting bad responses from thisper deployments is expected, as thisper deployments restarts thisper and nginx will throw errors."
+             echo "However, if it continues too long, check jenkins logs as it may be a problem with the deployment."
+           else
+             echo "Job failed. Check Jenkins logs for more information."
+             curl --location --request GET "${{ env.url }}/poll_deploy_job_status" --header 'Content-Type: application/json' --data '{"auth_usr": "github", "auth_key": "${{ secrets.JENKINS_AUTH_KEY }}", ${{ env.service_name }}, "job_id": "${job_id}"}'
+             exit 1
+           fi
 
   build_and_push_container:
     name: Build and Push Docker Container to ECR
